define([], function() {
    return {
      PropertyPaneDescription: "Les propriétés ci-dessous vous aideront à gérer vos questions de sondage et les fonctionnalités supplémentaires que vous pouvez exploiter.",
      BasicGroupName: "",
      ListCreationText: "Vérification de la liste de réponses...",
      PlaceholderIconText: "Configurez votre sondage rapide",
      PlaceholderDescription: "",
      PlaceholderButtonLabel: "Allez...",
      QuestionLoadingText: "Chargement des données du sondage",
      SubmissionLoadingText: "La soumission est en cours",
      PlsWait: "S'il vous plaît, attendez...",
      PollDateLabel: "Afficher le sondage en fonction de la date",
      PollDateCalloutText: "L'activation affichera les sondages en fonction de la 'Date de Début' & 'Date de Fin'",
      PollQuestionsLabel: "Questions du sondage:",
      PollQuestionsPanelHeader: "Liste des questions du sondage",
      PollQuestionsManageButton: "Gérer les informations sur les questions",
      MsgAfterSubmissionLabel: "Message de réussite:",
      MsgAfterSubmissionDescription: "Message à afficher après soumission réussie. Un maximum de 150 caractères est autorisé.",
      MsgAfterSubmissionPlaceholder: "Message...",
      ResponseMsgToUserLabel: "Response Message:",
      ResponseMsgToUserDescription: "Message displayed once the user submitted the poll. E.g., 'You voted for: <User Response>'",
      ResponseMsgToUserPlaceholder: "Message...",
      DefaultResponseMsgToUser: "Vous avez voté pour",
      SuccessfullVoteSubmission: "Merci pour votre soumission",
      FailedVoteSubmission: "Désolé, une erreur s'est produite lors de la soumission. Veuillez réessayer après un certain temps.",
      BtnSumbitVote: "Soumettre Voter",
      BtnSumbitVoteLabel: "Soumettre le texte du bouton:",
      BtnSumbitVoteDescription: "Texte à afficher sur le bouton d'envoi. Un maximum de 50 caractères est autorisé",
      BtnSumbitVotePlaceholder: "Soumettre le texte du bouton...",
      SubmitValidationMessage: "Veuillez sélectionner une option!",
      ChartFieldLabel: "Type de graphique préféré",
      ChartFieldCalloutText: "Sélectionnez le type de graphique préféré",
      NoPollMsgLabel: "Aucun message de sondage:",
      NoPollMsgDescription: "Message à afficher lorsqu'il n'y a pas de sondages.",
      NoPollMsgPlaceholder: "Message...",
      NoPollMsgDefault: "Désolé, aucun sondage à afficher!",
  
      Q_Title_Title: "Titre de Question",
      Q_Title_Placeholder: "Titre de Question...",
      Q_Options_Title: "Choix",
      Q_Options_Placeholder: "Choix séparés par une virgule",
      MultiChoice_Title: "Sélection multiple",
      Q_StartDate_Title: "Date de Début",
      Q_EndDate_Title: "Date de Fin"
    }
  }
);